# Generated by Django 2.1.3 on 2018-12-13 19:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=ckeditor.fields.RichTextField(default='ioi'),
        ),
    ]
